# Generated by Django 5.0.1 on 2024-02-08 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('АРТ', 'АРТЁМ'), ('УССУР', 'УССУРИЙСК')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_num', models.CharField(max_length=4)),
                ('good_numbers', models.TextField()),
                ('count', models.FloatField()),
                ('unit', models.CharField(max_length=15)),
                ('stock', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='dvssapp.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('full_name', models.TextField(max_length=25)),
                ('job_title', models.CharField(max_length=25)),
                ('stock', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='dvssapp.stock')),
            ],
        ),
    ]
