# Generated by Django 5.0.1 on 2024-02-08 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvssapp', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='place',
            name='stock',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
