# Generated by Django 5.0.1 on 2024-02-08 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvssapp', '0004_remove_worker_stock_remove_place_stock_delete_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
