# Generated by Django 5.0.1 on 2024-02-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvssapp', '0005_delete_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_num', models.CharField(max_length=4)),
                ('good_numbers', models.TextField()),
                ('count', models.FloatField()),
                ('unit', models.CharField(max_length=15)),
            ],
        ),
    ]
