# Generated by Django 5.0.1 on 2024-02-08 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvssapp', '0007_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='stock',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='dvssapp.stock'),
        ),
        migrations.AddField(
            model_name='worker',
            name='stock',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='dvssapp.stock'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='city',
            field=models.CharField(choices=[('АРТ', 'АРТЁМ'), ('УССУР', 'УССУРИЙСК')], max_length=15),
        ),
        migrations.AlterField(
            model_name='worker',
            name='job_title',
            field=models.CharField(choices=[('ЗАВ. СКЛ', 'ЗАВЕДУЮЩИЙ СКЛАДА'), ('КЛАДОВ', 'КЛАДОВЩИК')], max_length=25),
        ),
    ]
