# Generated by Django 5.0.1 on 2024-02-08 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvssapp', '0008_place_stock_worker_stock_alter_stock_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='stock',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='dvssapp.stock'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='stock',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='dvssapp.stock'),
        ),
    ]
