# Generated by Django 5.0.1 on 2024-02-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvssapp', '0009_alter_place_stock_alter_worker_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='city',
            field=models.CharField(choices=[('АРТЁМ', 'АРТЁМ'), ('УССУРИЙСК', 'УССУРИЙСК')], max_length=15),
        ),
        migrations.AlterField(
            model_name='worker',
            name='job_title',
            field=models.CharField(choices=[('ЗАВ. СКЛ', 'ЗАВЕДУЮЩИЙ СКЛАДА'), ('КЛАДОВЩИК', 'КЛАДОВЩИК')], max_length=25),
        ),
    ]
