# Generated by Django 5.0.1 on 2024-02-08 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvssapp', '0010_alter_stock_city_alter_worker_job_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='stock',
            new_name='stock_id',
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='stock',
            new_name='stock_id',
        ),
    ]
